import sqlalchemy

db = 'postgresql://alex:1619@localhost:5432/test1'
engine = sqlalchemy.create_engine(db)
connection = engine.connect()


connection.execute("""INSERT INTO artist (name) VALUES ('Berserkyd');""")
connection.execute("""INSERT INTO artist (name) VALUES ('Slaughter to Prevail');""")
connection.execute("""INSERT INTO artist (name) VALUES ('Free Flow Flava');""")
connection.execute("""INSERT INTO artist (name) VALUES ('ДДТ');""")
connection.execute("""INSERT INTO artist (name) VALUES ('БИ2');""")
connection.execute("""INSERT INTO artist (name) VALUES ('Сектор Газа');""")
connection.execute("""INSERT INTO artist (name) VALUES ('Rammstein');""")
connection.execute("""INSERT INTO artist (name) VALUES ('Linkin Park');""")

connection.execute("""INSERT INTO musical_genre (name) VALUES ('Metal');""")
connection.execute("""INSERT INTO musical_genre (name) VALUES ('Hip-Hop');""")
connection.execute("""INSERT INTO musical_genre (name) VALUES ('Alternative');""")
connection.execute("""INSERT INTO musical_genre (name) VALUES ('Punk rock');""")
connection.execute("""INSERT INTO musical_genre (name) VALUES ('Industrial metal');""")

connection.execute("""INSERT INTO album (name, year) VALUES ('LightWeight', 2018);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Kostolom', 2021);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Fuji', 2019);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Это всё', 1995);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Иномарки', 2004);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Колхозный панк', 1991);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Mutter', 2001);""")
connection.execute("""INSERT INTO album (name, year) VALUES ('Meteora', 2020);""")

connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (1, 'Apocalypse Thunder Bear', 222);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (1, 'Brotherhood of Death', 233);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (2, 'Bonebreaker', 265);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (2, 'Baba Yaga', 255);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (3, 'Nayami', 216);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (3, 'Sagari', 172);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (4, 'Ветер', 291);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (4, 'Белая ночь', 413);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (5, 'Революция', 217);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (5, 'Песок', 257);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (6, 'Моя смерть', 213);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (6, 'Местные', 184);""")

connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (7, 'Sonne', 273);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (8, 'Faint', 162);""")
connection.execute("""INSERT INTO track (album_id, name, duration_sec) VALUES (8, 'Breaking the Habit', 196);""")

connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Русский рок', 2019);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Heavy Metal', 2014);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Странный сборник', 1996);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Зарубежная музыка', 2017);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Япония и Германия', 1999);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Микс', 2022);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Старые песни', 1990);""")
connection.execute("""INSERT INTO music_collection (name, year) VALUES ('Без слов', 2022);""")

connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (1, 1);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (2, 2);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (3, 3);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (4, 4);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (5, 5);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (6, 6);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (7, 7);""")
connection.execute("""INSERT INTO albumartist (album_id, artist_id) VALUES (8, 8);""")

connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (1, 1);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (1, 2);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (1, 8);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (2, 3);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (3, 1);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (3, 7);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (3, 8);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (4, 4);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (4, 5);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (4, 6);""")
connection.execute("""INSERT INTO genreartist (genre_id, artist_id) VALUES (5, 8);""")

connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (7, 1);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (8, 1);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (10, 1);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (11, 1);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (12, 1);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (1, 2);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (2, 2);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (3, 2);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (4, 2);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (10, 3);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (7, 3);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (14, 4);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (15, 4);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (16, 4);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (5, 5);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (6, 5);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (14, 5);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (14, 6);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (2, 6);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (8, 6);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (3, 6);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (7, 7);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (8, 7);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (11, 7);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (12, 7);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (1, 8);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (2, 8);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (5, 8);""")
connection.execute("""INSERT INTO trackcollection (track_id, collection_id) VALUES (6, 8);""")